language: bash

dist: xenial
services:
  - docker

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash

script:
  - kernDups="$(files/kernel-config.d/.check-dups.sh)" && [ -z "$kernDups" ] || { echo >&2 "KERNEL CONFIG DUPLICATES!"; echo >&2 "$kernDups"; false; }
  - |
    set -e
    docker build -t boot2docker/boot2docker .
    docker run --rm boot2docker/boot2docker > boot2docker.iso

after_script:
  - docker images
  - ls -lh boot2docker.iso

# vim:set et ts=2 sw=2:
